# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: PQCP Build and Test
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  OPENHITLS_DIR: platform/openhitls
  SECURE_C_DIR: platform/openhitls/platform/Secure_C

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Download OpenHiTLS
      run: |
        mkdir -p ${{ github.workspace }}/platform
        cd ${{ github.workspace }}/platform
        git clone --recurse-submodules https://gitcode.com/openhitls/openhitls.git

    - name: Build Secure_C
      run: |
        cd ${{ github.workspace }}/${{ env.SECURE_C_DIR }}
        make -j$(nproc)

    - name: Build OpenHiTLS
      run: |
        mkdir -p ${{ github.workspace }}/${{ env.OPENHITLS_DIR }}/build
        cd ${{ github.workspace }}/${{ env.OPENHITLS_DIR }}/build
        python3 ../configure.py --enable \
          hitls_bsl hitls_crypto hitls_tls hitls_pki hitls_auth \
          --lib_type shared \
          --add_options="-DHITLS_EAL_INIT_OPTS=9 -DHITLS_CRYPTO_ASM_CHECK" \
          --add_link_flags="-L${{ github.workspace }}/${{ env.SECURE_C_DIR }}/lib -ldl" \
          --bits=64 --system=linux
        cmake ..
        make -j$(nproc)

    - name: Configure CMake
      run: |
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake .. \
          -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}" \
          -DENABLE_ASAN="OFF" \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/${{ env.OPENHITLS_DIR }};${{ github.workspace }}/${{ env.SECURE_C_DIR }}"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pqcp-build
        path: ${{ github.workspace }}/build
        retention-days: 5

